name = "After Dark"
license = "WTFPL"
licenselink = "https://codeberg.org/vhs/after-dark/src/branch/master/COPYING"
description = "A deceptively simple dark theme for Hugo."
homepage = "https://codeberg.org/vhs/after-dark/"
tags = [
  "personal",
  "simple",
  "minimal",
  "responsive",
  "accessible",
  "search",
  "dark",
  "blog"
]
features = [
  "Module System",
  "Lazy Loading",
  "BPG Image Support",
  "Social Engagement",
  "Search Optimization",
  "Post Images",
  "Fuzzy Search",
  "Personalization",
  "Content Reuse",
  "Related Content",
  "Table of Contents",
  "Section Menu",
  "Comments",
  "Modification Dating",
  "Syntax Highlighting",
  "Taxonomy Pages",
  "Error Page",
  "Pagination",
  "Reading time",
  "Post Bylines"
]
min_version = 0.44

[author]
  name = "VHS"
  homepage = "https://vhs.codeberg.page"
