name = "After Dark"
license = "WTFPL"
licenselink = "https://codeberg.org/vhs/after-dark/blob/master/COPYING"
description = "A robust, elegant dark theme for Hugo."
homepage = "https://vhs.github.io/after-dark/"
tags = [
  "minimal",
  "responsive",
  "accessible",
  "terminal"
  "dark"
]
features = [
  "Mobile-optimized",
  "SEO-optimized",
  "Responsive Design",
  "Flexbox Layouts",
  "Google Analytics",
  "Disqus",
  "Image lazyloading",
  "OpenGraph",
  "Schema Structured Data",
  "Pagination",
  "Reading time",
  "Related content",
  "Modification dating",
  "Author byline",
  "Word Count",
  "Related Posts",
  "Section Menu",
  "Block Templates",
  "Table of Contents",
  "Custom Shortcodes",
  "Keyboard Accessibility",
  "Inclusive Design",
  "Theme Variants"
]
min_version = 0.16

[author]
  name = "VHS"
  homepage = "https://vhs.codeberg.page"
