name = "After Dark"
license = "WTFPL"
licenselink = "https://choosealicense.com/licenses/wtfpl/"
description = "A deceptively simple dark theme for Hugo."
homepage = "https://codeberg.org/vhs/after-dark/"
tags = [
  "personal",
  "minimal",
  "responsive",
  "accessible",
  "dark",
  "search",
  "blog"
]
features = [
  "Quick Installer",
  "Module System",
  "Section Menu"
  "Theme Variants",
  "Custom Styles",
  "Trim Color",
  "Fuzzy Search",
  "Code Highlighter",
  "Post Images",
  "Lazy Loading",
  "Social Engagement",
  "Search Optimization",
  "Modification Dating",
  "Index Blocking",
  "Referrer Policy",
  "Snippets",
  "Related Content",
  "Table of Contents",
  "SVG Favicon",
  "404 Page"
]
min_version = 0.44

[author]
  name = "VHS"
  homepage = "https://vhs.codeberg.page"
