name = "After Dark"
license = "ISC"
licenselink = "https://codeberg.org/vhs/after-dark/blob/master/LICENSE.md"
description = "A simple, yet highly configurable responsive dark theme."
homepage = "https://vhs.github.io/after-dark/"
tags = [
  "personal",
  "minimal",
  "responsive",
  "accessible",
  "vaporwave",
  "unported",
  "blog",
  "disqus",
  "syntax highlighting",
  "technical",
  "dark",
  "custom themes"
]
features = [
  "Mobile-optimized",
  "SEO-optimized",
  "Responsive Design",
  "Flexbox Layouts",
  "Google Analytics",
  "Disqus",
  "Image lazyloading",
  "OpenGraph",
  "Schema Structured Data",
  "Pagination",
  "Reading time",
  "Related content",
  "Modification dating",
  "Author byline",
  "Word Count",
  "Related Posts",
  "Section Menu",
  "Block Templates",
  "Table of Contents",
  "Keyboard accessible",
  "Terminal friendly",
  "Customizable theme"
]
min_version = 0.16

[author]
  name = "VHS"
  homepage = "https://vhs.codeberg.page"
