baseurl = "https://vhs.codeberg.page/after-dark/" # Controls base URL sitewide
title = "After Dark" # Homepage title and page title suffix
paginate = 33 # Number of items to show before paginating

# Controls default theme and theme components
theme = [
  "after-dark"
]

disableLiveReload = false # Optional, set true to disable live reload
enableRobotsTXT = true # Suggested, enable robots.txt file

pygmentsCodefences = true # Suggested, highlight fenced code blocks
pygmentsUseClasses = true # Required for custom syntax highlighting

sectionPagesMenu = "main" # Enable menu system for lazy bloggers
footnoteReturnLinkContents = "↩" # Provides a nicer footnote return link

[languages.en]
  languageCode = "en-US" # Controls site language
  languageName = "English"
[languages.id]
  languageCode = "id-ID" # Controls site language
  languageName = "Indonesia"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  description = "After Dark is free and open-source software you can use to create a website, blog or app." # Suggested, controls default description meta
  author = "VHS" # Optional, controls author name display on posts
  hide_author = true # Optional, set true to hide author name on posts
  has_cookies = false # Optional, set true to disable cookie disclaimer
  disable_csp = false # Optional, set true to disable content security policy
  images = [
    "https://vhs.codeberg.page/after-dark/images/screenshots/after-dark-v6.15.0-homepage-fs8.png"
  ] # Suggested, controls default Open Graph images

[params.layout.menu.main]
  hidden = false # Optional, set false or remove to show section menu

[params.security.csp.directives]
  mediaSrc = [
    "https://vhs.keybase.pub"
  ]
  scriptSrc = [
    "'self'",
    "'unsafe-inline'",
    "https:",
    "'sha512-Jx/MqTxYWqHdoOkHItRJJZCvFDhERPr5gG4I5ESu3V&#43;BgQyAQ6wXfdsGzhzmT0yyvkAWz2jbrn81q90RRJTSTg=='",
    "'sha512-hno7WeTIciCJSjg/myjyK30HYkrcGCVwo4g4SpUalvrs3r2lS7bPNIQwbCNypKbg7BZ1sA4AsGnk6Gq4NOKpGA=='",
    "'sha512-ISTAV0GadOIz/NXXHOS&#43;eCM0ysXVVHhQTlvA6LJxz/DeA5yIxm0Vqf5IE&#43;WH0yuuXkayAKtoZkQ326nch5f/fg=='",
    "'strict-dynamic'"
  ]

[params.seo.webmaster_verifications]
  yandex = "4006a8813cbb9fdb" # https://webmaster.yandex.com/

[[menu.main]]
  name = "Overview"
  weight = 1
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Features"
  weight = 2
  identifier = "feature"
  url = "/feature/"
[[menu.main]]
  name = "Modules"
  weight = 3
  identifier = "module"
  url = "/module/"
[[menu.main]]
  name = "Shortcodes"
  weight = 4
  identifier = "shortcode"
  url = "/shortcode/"
[[menu.main]]
  name = "Extras"
  weight = 5
  identifier = "extra"
  url = "/extra/"
[[menu.main]]
  name = "Search"
  weight = 6
  identifier = "search"
  url = "/search/"
